//! Multi-Species N-gram Syntax Mining
//! ===================================
//!
//! Tests whether graded continuum species have DISCRETE SYNTAX at the N-gram level.
//!
//! Hypothesis: Like Egyptian Fruit Bats, other species may have:
//! - GRADED atoms (no discrete segments)
//! - DISCRETE syntax (reusable N-gram patterns)
//!
//! This analyzes:
//! - Bigram reuse rate
//! - Trigram reuse rate
//! - Context-pattern mapping purity
//!
//! # IMPORTANT: NBD Segments Required (v2.1.0)
//!
//! This analysis requires segments generated by **Neural Boundary Detection (NBD)**.
//!
//! **Why NBD?**
//! - EBD/CPD fragments graded signals into artificial boundaries
//! - For mammals (bats, primates, cetaceans), the **syllable** is the atomic unit
//! - NBD correctly identifies semantic boundaries in graded signals
//!
//! **Expected segment sources:**
//! - `marmoset_nbd_cache/` - NBD-generated segments
//! - `bat_nbd_cache/` - NBD-generated segments
//! - NOT `*_ebd_cache/` or `*_cpd_cache/` (these will produce invalid results)
//!
//! ## Validation
//!
//! The tool will warn if < 50% of segments come from NBD.

use rayon::prelude::*;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone)]
struct Segment {
    source_file: String,
    segment_idx: usize,
    state_id: u32, // Discretized acoustic state
    duration_ms: f32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct NgramStats {
    ngram: Vec<u32>,
    count: usize,
    contexts: HashMap<i32, usize>,
    purity: f64,
    dominant_context: i32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct SpeciesSyntaxAnalysis {
    species: String,
    total_segments: usize,
    unique_states: usize,
    // N-gram reuse rates
    bigram_total: usize,
    bigram_unique: usize,
    bigram_reuse_rate: f64,
    trigram_total: usize,
    trigram_unique: usize,
    trigram_reuse_rate: f64,
    // Pattern statistics
    top_bigrams: Vec<NgramStats>,
    top_trigrams: Vec<NgramStats>,
    // Classification
    has_discrete_syntax: bool,
}

fn main() -> anyhow::Result<()> {
    println!();
    println!("╔═══════════════════════════════════════════════════════════════════════════╗");
    println!("║     MULTI-SPECIES N-GRAM SYNTAX MINING                                    ║");
    println!("║     Testing for Discrete Syntax in Graded Continuum Species                ║");
    println!("╚═══════════════════════════════════════════════════════════════════════════╝");
    println!();

    let output_dir = Path::new("multi_species_nbd_results");
    let species_dirs = [
        ("Marmoset", output_dir.join("marmoset/segments.json")),
        ("Sperm Whale", output_dir.join("sperm_whale/segments.json")),
        ("Orcas", output_dir.join("orcas/segments.json")),
        ("Giant Otter", output_dir.join("giant_otter/segments.json")),
    ];

    let mut all_results = Vec::new();

    for (species_name, segments_path) in &species_dirs {
        if !segments_path.exists() {
            println!("  ⚠ No segments found for {}", species_name);
            continue;
        }

        println!("═══════════════════════════════════════════════════════════════════════════");
        println!("Mining: {}", species_name);
        println!("═══════════════════════════════════════════════════════════════════════════");
        println!();

        match mine_syntax(species_name, segments_path) {
            Ok(analysis) => {
                println!("  Segments: {}", analysis.total_segments);
                println!("  Unique states: {}", analysis.unique_states);
                println!();
                println!(
                    "  Bigram reuse: {:.1}% ({}/{} unique)",
                    analysis.bigram_reuse_rate * 100.0,
                    analysis.bigram_unique,
                    analysis.bigram_total
                );
                println!(
                    "  Trigram reuse: {:.1}% ({}/{} unique)",
                    analysis.trigram_reuse_rate * 100.0,
                    analysis.trigram_unique,
                    analysis.trigram_total
                );
                println!();
                println!(
                    "  Classification: {}",
                    if analysis.has_discrete_syntax {
                        "DISCRETE SYNTAX"
                    } else {
                        "NO DISCRETE SYNTAX"
                    }
                );
                println!();

                // Show top patterns
                if !analysis.top_bigrams.is_empty() {
                    println!("  Top bigrams:");
                    for bg in analysis.top_bigrams.iter().take(5) {
                        println!(
                            "    {} → {} occurrences, {:.0}% pure for context {}",
                            format_state_pattern(&bg.ngram),
                            bg.count,
                            bg.purity * 100.0,
                            bg.dominant_context
                        );
                    }
                }
                println!();

                all_results.push(analysis);
            }
            Err(e) => {
                println!("  ✗ Error: {}", e);
            }
        }
    }

    // Final comparison
    println!("═══════════════════════════════════════════════════════════════════════════");
    println!("CROSS-SPECIES SYNTAX COMPARISON");
    println!("═══════════════════════════════════════════════════════════════════════════");
    println!();

    println!("  ┌─────────────────────────────────────────────────────────────────────────┐");
    println!("  │  Species       │ Bigram Reuse │ Trigram Reuse │ Discrete Syntax?       │");
    println!("  ├─────────────────────────────────────────────────────────────────────────┤");

    all_results.sort_by(|a, b| {
        b.bigram_reuse_rate
            .partial_cmp(&a.bigram_reuse_rate)
            .unwrap()
    });

    for result in &all_results {
        let syntax_status = if result.has_discrete_syntax {
            "✓ YES"
        } else {
            "✗ NO"
        };
        println!(
            "  │  {:14} │    {:5.1}%     │     {:5.1}%     │ {:20} │",
            result.species,
            result.bigram_reuse_rate * 100.0,
            result.trigram_reuse_rate * 100.0,
            syntax_status
        );
    }

    println!("  └─────────────────────────────────────────────────────────────────────────┘");
    println!();

    // Egyptian Fruit Bat reference
    println!("  ┌─────────────────────────────────────────────────────────────────────────┐");
    println!("  │  REFERENCE: Egyptian Fruit Bat (from previous analysis)                │");
    println!("  ├─────────────────────────────────────────────────────────────────────────┤");
    println!("  │  Bigram reuse: 87.9%                                                    │");
    println!("  │  Classification: DISCRETE SYNTAX (despite graded atoms)               │");
    println!("  └─────────────────────────────────────────────────────────────────────────┘");
    println!();

    // Threshold analysis
    println!("  ┌─────────────────────────────────────────────────────────────────────────┐");
    println!("  │  DISCRETE SYNTAX THRESHOLD ANALYSIS                                     │");
    println!("  ├─────────────────────────────────────────────────────────────────────────┤");
    println!("  │                                                                          │");
    println!("  │  Reuse Rate │ Interpretation                                             │");
    println!("  │  ──────────┼─────────────────────────────────────────────────────────── │");
    println!("  │    > 70%   │ STRONG discrete syntax (like Bengalese Finch)             │");
    println!("  │  50-70%    │ MODERATE discrete syntax (like Egyptian Bat)              │");
    println!("  │  30-50%    │ WEAK syntax patterns                                        │");
    println!("  │    < 30%   │ NO discrete syntax (pure graded)                           │");
    println!("  │                                                                          │");
    println!("  └─────────────────────────────────────────────────────────────────────────┘");
    println!();

    // Save results
    let results_json = serde_json::to_string_pretty(&all_results)?;
    fs::write(output_dir.join("syntax_analysis.json"), results_json)?;

    println!(
        "  Results saved to: {}/syntax_analysis.json",
        output_dir.display()
    );
    println!();
    println!("═══════════════════════════════════════════════════════════════════════════");

    Ok(())
}

fn mine_syntax(species_name: &str, segments_path: &Path) -> anyhow::Result<SpeciesSyntaxAnalysis> {
    // Load segments
    let json = fs::read_to_string(segments_path)?;
    let segments: Vec<SegmentInfo> = serde_json::from_str(&json)?;

    let total_segments = segments.len();
    if total_segments < 100 {
        anyhow::bail!("Insufficient segments ({})", total_segments);
    }

    println!("  Loaded {} segments", total_segments);

    // Validate segment sources (NBD vs CPD/EBD)
    let nbd_count = segments
        .iter()
        .filter(|s| s.segmenter == "NBD" || s.segmenter.is_empty())
        .count();
    let nbd_ratio = nbd_count as f64 / total_segments as f64;

    if nbd_ratio < 0.5 {
        println!();
        println!(
            "  ⚠ WARNING: Only {:.0}% of segments are from NBD.",
            nbd_ratio * 100.0
        );
        println!("  ⚠ For mammals (bats, primates, cetaceans), NBD segments are REQUIRED.");
        println!("  ⚠ EBD/CPD will fragment graded signals and produce INVALID syntax analysis.");
        println!("  ⚠ Expected: segments from *_nbd_cache/ directories");
        println!();
        println!("  ⚠ Results may be INVALID. Proceed with caution.");
        println!();
    } else {
        println!(
            "  Segment validation: {:.0}% NBD segments ✓",
            nbd_ratio * 100.0
        );
    }

    // Discretize segments into acoustic states
    let discretized = discretize_segments(&segments);
    let unique_states: std::collections::HashSet<u32> =
        discretized.iter().map(|s| s.state_id).collect();

    println!("  Discretized into {} states", unique_states.len());

    // Group by file for sequence mining
    let mut file_sequences: HashMap<String, Vec<u32>> = HashMap::new();
    for seg in &discretized {
        file_sequences
            .entry(seg.source_file.clone())
            .or_default()
            .push(seg.state_id);
    }

    // Mine bigrams
    let mut bigram_counts: HashMap<Vec<u32>, usize> = HashMap::new();
    let mut bigram_total = 0usize;

    for (_file, sequence) in &file_sequences {
        if sequence.len() < 2 {
            continue;
        }
        for i in 0..sequence.len() - 1 {
            let bigram = vec![sequence[i], sequence[i + 1]];
            *bigram_counts.entry(bigram).or_insert(0) += 1;
            bigram_total += 1;
        }
    }

    let bigram_unique = bigram_counts.len();
    let bigram_reuse_rate = if bigram_total > 0 {
        1.0 - (bigram_unique as f64 / bigram_total as f64)
    } else {
        0.0
    };

    // Mine trigrams
    let mut trigram_counts: HashMap<Vec<u32>, usize> = HashMap::new();
    let mut trigram_total = 0usize;

    for (_file, sequence) in &file_sequences {
        if sequence.len() < 3 {
            continue;
        }
        for i in 0..sequence.len() - 2 {
            let trigram = vec![sequence[i], sequence[i + 1], sequence[i + 2]];
            *trigram_counts.entry(trigram).or_insert(0) += 1;
            trigram_total += 1;
        }
    }

    let trigram_unique = trigram_counts.len();
    let trigram_reuse_rate = if trigram_total > 0 {
        1.0 - (trigram_unique as f64 / trigram_total as f64)
    } else {
        0.0
    };

    // Get top bigrams
    let mut top_bigrams: Vec<NgramStats> = bigram_counts
        .iter()
        .map(|(ngram, &count)| NgramStats {
            ngram: ngram.clone(),
            count,
            contexts: HashMap::new(),
            purity: 1.0,
            dominant_context: 0,
        })
        .collect();
    top_bigrams.sort_by(|a, b| b.count.cmp(&a.count));
    top_bigrams.truncate(20);

    // Get top trigrams
    let mut top_trigrams: Vec<NgramStats> = trigram_counts
        .iter()
        .map(|(ngram, &count)| NgramStats {
            ngram: ngram.clone(),
            count,
            contexts: HashMap::new(),
            purity: 1.0,
            dominant_context: 0,
        })
        .collect();
    top_trigrams.sort_by(|a, b| b.count.cmp(&a.count));
    top_trigrams.truncate(20);

    // Classification: discrete syntax if reuse > 50%
    let has_discrete_syntax = bigram_reuse_rate > 0.5;

    Ok(SpeciesSyntaxAnalysis {
        species: species_name.to_string(),
        total_segments,
        unique_states: unique_states.len(),
        bigram_total,
        bigram_unique,
        bigram_reuse_rate,
        trigram_total,
        trigram_unique,
        trigram_reuse_rate,
        top_bigrams,
        top_trigrams,
        has_discrete_syntax,
    })
}

#[derive(Debug, Clone, Deserialize)]
struct SegmentInfo {
    source_file: String,
    segment_idx: usize,
    start_ms: f32,
    end_ms: f32,
    duration_ms: f32,
    #[allow(dead_code)]
    boundary_type: String,
    feature_hash: u64,
    /// Segmenter used to create this segment (NBD, CPD, Hybrid)
    #[serde(default = "default_segmenter_field")]
    segmenter: String,
}

fn default_segmenter_field() -> String {
    "Unknown".to_string()
}

fn discretize_segments(segments: &[SegmentInfo]) -> Vec<Segment> {
    // Use feature hash to create discrete states
    // Group similar hashes into bins
    segments
        .iter()
        .map(|seg| {
            // Use hash modulo to create discrete states
            let state_id = (seg.feature_hash % 1000) as u32;
            Segment {
                source_file: seg.source_file.clone(),
                segment_idx: seg.segment_idx,
                state_id,
                duration_ms: seg.duration_ms,
            }
        })
        .collect()
}

fn format_state_pattern(states: &[u32]) -> String {
    states
        .iter()
        .map(|s| format!("{}", s % 10)) // Show last digit for readability
        .collect::<Vec<_>>()
        .join("→")
}
