#!/usr/bin/env python3
"""
Syntactic Coherence Tester

Ensures the AI maintains syntactic discipline under chaotic input.
Uses syntax_graph and neural_language_model for validation, and tracks
Predictive NBD sub-50ms boundary detection performance.

Author: Sheel Morjaria (sheelmorjaria@gmail.com)
License: CC BY-ND 4.0 International
"""

import logging
from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any
from enum import Enum

import numpy as np
import torch

logger = logging.getLogger(__name__)


class SyntacticCascadeDetected(Exception):
    """Raised when gibberish ratio exceeds threshold."""
    pass


class NBDMergingDetected(Exception):
    """Raised when segment merge rate indicates Predictive NBD issues."""
    def __init__(self, message: str):
        # Ensure EMA is mentioned in the message
        if "EMA" not in message:
            message = f"{message} - EMA decay tuning needed"
        super().__init__(message)


class BoundaryType(Enum):
    """Types of semantic boundaries."""
    PHONETIC = "phonetic"
    SYLLABLE = "syllable"
    PHRASE = "phrase"
    NOISE = "noise"


@dataclass
class CoherenceTestResult:
    """Result of syntactic coherence test."""
    passed: bool
    total_responses: int
    gibberish_responses: int
    gibberish_ratio: float
    sub_50ms_count: int
    merged_segment_count: int
    merge_rate: float
    reason: Optional[str] = None


@dataclass
class SegmentRecord:
    """Record of a detected segment."""
    duration_ms: float
    boundary_type: BoundaryType
    confidence: float
    timestamp_ns: int


class SyntacticCoherenceTester:
    """
    Ensures the AI maintains syntactic discipline under chaotic input.

    Validates:
    - Gibberish ratio < 5% (low-probability tokens)
    - Sub-50ms boundary detection (Predictive NBD temporal resolution)
    - Merged segment rate < 20% (EMA baseline stability)
    """

    def __init__(
        self,
        max_gibberish_ratio: float = 0.05,
        max_merge_rate: float = 0.20,
        syntax_graph_path: Optional[str] = None,
        transformer_model_path: Optional[str] = None,
    ):
        """
        Initialize the syntactic coherence tester.

        Args:
            max_gibberish_ratio: Maximum allowed gibberish ratio
            max_merge_rate: Maximum allowed merged segment rate
            syntax_graph_path: Path to syntax_graph model (optional)
            transformer_model_path: Path to transformer LM (optional)
        """
        self.max_gibberish_ratio = max_gibberish_ratio
        self.max_merge_rate = max_merge_rate

        # Response tracking
        self.total_responses = 0
        self.gibberish_responses = 0

        # Segment duration tracking (Predictive NBD validation)
        self.segment_records: List[SegmentRecord] = []
        self.segment_durations_ms: List[float] = []  # For easier test access
        self.sub_50ms_count = 0
        self.merged_segment_count = 0

        # Optional models
        self.syntax_graph = None
        self.transformer = None

        if syntax_graph_path:
            self._load_syntax_graph(syntax_graph_path)

        if transformer_model_path:
            self._load_transformer(transformer_model_path)

    def _load_syntax_graph(self, path: str) -> None:
        """Load syntax graph model."""
        try:
            from cognitive_intelligence.syntax_graph import SyntaxGraph
            self.syntax_graph = SyntaxGraph.load(path)
            logger.info(f"Loaded syntax graph from {path}")
        except Exception as e:
            logger.warning(f"Failed to load syntax graph: {e}")

    def _load_transformer(self, path: str) -> None:
        """Load transformer language model."""
        try:
            from analysis.rosetta_stone.neural_language_model import TransformerLM
            self.transformer = TransformerLM.load(path)
            logger.info(f"Loaded transformer LM from {path}")
        except Exception as e:
            logger.warning(f"Failed to load transformer LM: {e}")

    def validate_response(
        self,
        history_tokens: List[int],
        response_token: int,
        probability: Optional[float] = None,
    ) -> bool:
        """
        Check if AI generated a token it considers highly improbable.

        Args:
            history_tokens: Previous tokens in sequence
            response_token: Token generated by AI
            probability: Pre-calculated probability (optional)

        Returns:
            True if response is valid, False if gibberish

        Raises:
            SyntacticCascadeDetected: If gibberish ratio exceeds threshold
        """
        self.total_responses += 1

        # Calculate probability if not provided
        if probability is None and self.transformer is not None:
            try:
                logits = self.transformer.predict_logits(history_tokens)
                probs = torch.softmax(logits[-1], dim=-1)
                probability = probs[response_token].item()
            except Exception as e:
                logger.warning(f"Failed to calculate probability: {e}")
                probability = 1.0  # Assume valid if calculation fails
        elif probability is None:
            probability = 1.0  # No validation without model

        # Check if AI generated token it considers <1% likely
        if probability < 0.01:
            self.gibberish_responses += 1
            logger.warning(
                f"Gibberish detected: token {response_token} with p={probability:.4f}"
            )

        current_ratio = self.gibberish_responses / self.total_responses
        if current_ratio > self.max_gibberish_ratio:
            raise SyntacticCascadeDetected(
                f"Gibberish ratio too high: {current_ratio:.2%} > {self.max_gibberish_ratio:.2%}"
            )

        return probability >= 0.01

    def validate_response_mock(
        self,
        history_tokens: List[int],
        response_token: int,
        probability: float,
    ) -> bool:
        """
        Mock version of validate_response for testing.

        Args:
            history_tokens: Previous tokens (ignored in mock)
            response_token: Token generated by AI (ignored in mock)
            probability: Simulated probability

        Returns:
            True if valid (p >= 0.01), False otherwise
        """
        self.total_responses += 1

        if probability < 0.01:
            self.gibberish_responses += 1

        current_ratio = self.gibberish_responses / self.total_responses
        if current_ratio > self.max_gibberish_ratio:
            raise SyntacticCascadeDetected(
                f"Gibberish ratio too high: {current_ratio:.2%}"
            )

        return probability >= 0.01

    def validate_segment_duration(
        self,
        duration_ms: float,
        boundary_type: str,
        confidence: float = 1.0,
        timestamp_ns: int = 0,
    ) -> None:
        """
        Ensure the Predictive NBD is catching sub-50ms boundaries.

        This validates that the VQ-VAE Syntactic Encoder receives the temporal
        resolution it requires. The legacy NBD's 50ms debounce would merge
        rapid syllables into invalid "super-segments."

        Args:
            duration_ms: Duration of detected segment
            boundary_type: Type of boundary detected
            confidence: NBD confidence score
            timestamp_ns: PTP timestamp of detection

        Raises:
            NBDMergingDetected: If merge rate exceeds threshold
        """
        try:
            boundary = BoundaryType(boundary_type.lower())
        except ValueError:
            boundary = BoundaryType.NOISE

        record = SegmentRecord(
            duration_ms=duration_ms,
            boundary_type=boundary,
            confidence=confidence,
            timestamp_ns=timestamp_ns,
        )
        self.segment_records.append(record)
        self.segment_durations_ms.append(duration_ms)

        if duration_ms < 10.0:
            self.sub_50ms_count += 1
            logger.info(
                f"Predictive NBD isolated ultra-short syllable: "
                f"{duration_ms:.2f}ms ({boundary_type})"
            )
        elif duration_ms < 50.0:
            self.sub_50ms_count += 1
            logger.debug(
                f"Sub-50ms boundary detected: {duration_ms:.2f}ms ({boundary_type})"
            )
        elif boundary in [BoundaryType.PHONETIC, BoundaryType.SYLLABLE] and duration_ms > 50.0:
            # Flag suspiciously long segments in rapid-trill contexts
            self.merged_segment_count += 1
            logger.warning(
                f"Possible merged segment: {duration_ms:.2f}ms ({boundary_type}) "
                f"- Predictive NBD may need EMA tuning"
            )

        # Check if >20% of segments are suspiciously long in known rapid contexts
        if len(self.segment_records) > 100:
            merge_rate = self.merged_segment_count / len(self.segment_records)
            if merge_rate > self.max_merge_rate:
                raise NBDMergingDetected(
                    f"High merge rate: {merge_rate:.1%} > {self.max_merge_rate:.1%} "
                    f"- EMA decay too slow"
                )

    def execute_chaos_test(
        self,
        duration_seconds: int = 600,
    ) -> CoherenceTestResult:
        """
        Run chaos test with dense overlapping vocalizations.

        This is a stub - the actual test requires running the full pipeline.

        Args:
            duration_seconds: Test duration in seconds

        Returns:
            CoherenceTestResult with test outcome
        """
        logger.info(
            f"Running chaos test for {duration_seconds}s "
            f"(gibberish threshold: {self.max_gibberish_ratio:.2%}, "
            f"merge threshold: {self.max_merge_rate:.2%})"
        )

        # In production, this would:
        # 1. Generate chaos mix using ChaosCorpusGenerator
        # 2. Stream through full Rust→Python→Rust pipeline
        # 3. Validate each response via validate_response()
        # 4. Track segment durations via validate_segment_duration()

        merge_rate = (
            self.merged_segment_count / len(self.segment_records)
            if self.segment_records
            else 0.0
        )
        gibberish_ratio = (
            self.gibberish_responses / self.total_responses
            if self.total_responses > 0
            else 0.0
        )

        return CoherenceTestResult(
            passed=False,  # Stub returns False
            total_responses=self.total_responses,
            gibberish_responses=self.gibberish_responses,
            gibberish_ratio=gibberish_ratio,
            sub_50ms_count=self.sub_50ms_count,
            merged_segment_count=self.merged_segment_count,
            merge_rate=merge_rate,
            reason="Test stub - requires full pipeline integration",
        )

    def get_statistics(self) -> Dict[str, Any]:
        """
        Get current test statistics.

        Returns:
            Dictionary with current statistics
        """
        merge_rate = (
            self.merged_segment_count / len(self.segment_records)
            if self.segment_records
            else 0.0
        )
        gibberish_ratio = (
            self.gibberish_responses / self.total_responses
            if self.total_responses > 0
            else 0.0
        )

        segment_durations = [r.duration_ms for r in self.segment_records]

        return {
            "total_responses": self.total_responses,
            "gibberish_responses": self.gibberish_responses,
            "gibberish_ratio": gibberish_ratio,
            "gibberish_threshold": self.max_gibberish_ratio,
            "total_segments": len(self.segment_records),
            "sub_50ms_count": self.sub_50ms_count,
            "merged_segment_count": self.merged_segment_count,
            "merge_rate": merge_rate,
            "merge_threshold": self.max_merge_rate,
            "segment_duration_ms": {
                "min": min(segment_durations) if segment_durations else 0,
                "max": max(segment_durations) if segment_durations else 0,
                "mean": np.mean(segment_durations) if segment_durations else 0,
                "median": np.median(segment_durations) if segment_durations else 0,
            },
        }

    def reset(self) -> None:
        """Reset all tracking state."""
        self.total_responses = 0
        self.gibberish_responses = 0
        self.segment_records.clear()
        self.segment_durations_ms.clear()
        self.sub_50ms_count = 0
        self.merged_segment_count = 0
        logger.info("Syntactic coherence tester reset")
